spring:
  servlet:
    multipart:
      max-file-size: 800MB
      max-request-size: 800MB

  cache:
    type: caffeine

  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

storage.directory: ${DATA_DIR}
dump.directory: ${DUMP_DIR}
node.service.url: ${NODE_SERVICE_URL}
node.service.execute: /exec
node.service.validate: /validate
node.service.load_nodes: /load_nodes
node.service.load_graphs: /load_graphs
processing.topic: /topic/processing/
node.cache: nodeCache
scan.schedule: 0 */1 * * * *
cleanup.schedule: 0 */1 * * * *
scan.directory.schedule: 0 */1 * * * *
retention-months: 6
conn.encrypt.key: 16charslongkey!!
execution.graph.mode: level
execution.node.mode: async

logging:
  level:
    org.springframework.web: INFO
    org.springframework.boot.actuate: INFO

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]